name: Unstarred Notify
on:
  watch:
    types: [starred]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Notify by email
        run: |
          echo "Watch event type: ${{ github.event.action }}"
         
