name: starred Notify
on:
  watch:
    types: [started]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: download
        run: |
          wget "https://github.com/matt-repository/star_notify_email/releases/download/v1/star_notify_email"
      - name: Notify by email
        run: |
          chmod +x star_notify_email
          ./star_notify_email -token ${{github.token}} -sendMailbox ${{secrets.MY_EMAIL}} -receiveMailbox ${{secrets.MY_EMAIL}} -password ${{secrets.MY_EMAIL_AUTHORIZATION_CODE}}
         
