name: Started Notify
on:
  watch:
    types: [started, starred, unstarred]
jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Notify by email
        run: |
          echo "Watch event type: ${{ github.event.action }}"
          echo "Sender: ${{ github.event.sender.login }}"
